2022-06-06 14:42:14,738 INFO    MainThread:4366 [wandb_setup.py:_flush():76] Loading settings from /Users/shibo/.config/wandb/settings
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_setup.py:_flush():76] Loading settings from /Users/shibo/Documents/Reinforcement-Learning/project/wandb/settings
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'project/rl_cuts.py', 'program': 'rl_cuts.py'}
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_init.py:_log_setup():428] Logging user logs to /Users/shibo/Documents/Reinforcement-Learning/project/wandb/run-20220606_144214-22e45kx5/logs/debug.log
2022-06-06 14:42:14,739 INFO    MainThread:4366 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/shibo/Documents/Reinforcement-Learning/project/wandb/run-20220606_144214-22e45kx5/logs/debug-internal.log
2022-06-06 14:42:14,740 INFO    MainThread:4366 [wandb_init.py:init():462] calling init triggers
2022-06-06 14:42:14,740 INFO    MainThread:4366 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-06 14:42:14,740 INFO    MainThread:4366 [wandb_init.py:init():515] starting backend
2022-06-06 14:42:14,740 INFO    MainThread:4366 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-06 14:42:14,760 INFO    MainThread:4366 [backend.py:ensure_launched():217] starting backend process...
2022-06-06 14:42:14,773 INFO    MainThread:4366 [backend.py:ensure_launched():222] started backend process with pid: 4482
2022-06-06 14:42:14,775 INFO    MainThread:4366 [wandb_init.py:init():525] backend started and connected
2022-06-06 14:42:14,782 INFO    MainThread:4366 [wandb_init.py:init():596] updated telemetry
2022-06-06 14:42:14,821 INFO    MainThread:4366 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-06 14:42:44,826 INFO    MainThread:4366 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-06 14:42:44,827 ERROR   MainThread:4366 [wandb_init.py:init():636] backend process timed out
2022-06-06 14:42:44,827 ERROR   MainThread:4366 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-06 14:42:44,851 ERROR   MainThread:4366 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/shibo/opt/anaconda3/envs/rl_cut/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
